#! /bin/sh

ACCESS_TOKEN=$1
ACCOUNT_ID=$2
START_DATE=$3 # "2021-08-09"
END_DATE=$4 # "2021-08-29"
PROJECT_ID=${5:-4948863}   # Internal
TASK_ID=${6-2990320}      # Vacation

usage() {
    echo "Usage: $0 <access_token> <account_id> <start_date> <end_date> [<project_id> [<task_id>]]"
    echo "  <access_token>   - access token from harvest"
    echo "  <account_id>     - account ID from harvest"
    echo "  <start_date>     - start date in yyyy-mm-dd format"
    echo "  <end_date>       - end date in yyyy-mm-dd format"
    echo "  <project_id>     - project ID from harvest (default: 4948863)"
    echo "  <task_id>        - task ID from harvest (default: 2990320)"
    echo "Example"
    echo "  $0 <access_token> <account_id> 2020-01-01 2020-01-31"
    exit 1
}

if [ -z "$START_DATE" ] || [ -z "$END_DATE" ] || [ -z "$ACCESS_TOKEN" ] || [ -z "$ACCOUNT_ID" ]; then
    usage
    exit 1
fi

END=$(date -d "$END_DATE" "+%s")
CURRENT=$(date -d "$START_DATE" "+%s")

while [ $CURRENT -le $END ]; do
    TMP_DATE=$(date -I -d @$CURRENT)
    DAY_OF_WEEK=$(date -d $TMP_DATE "+%u")

    if [ $DAY_OF_WEEK -le 5 ]; then
        curl "https://api.harvestapp.com/v2/time_entries" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Harvest-Account-Id: $ACCOUNT_ID" \
            -H "User-Agent: harvest_bulk" \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{"project_id":'"$PROJECT_ID"',"task_id":'"$TASK_ID"',"spent_date":"'"$TMP_DATE"'","started_time":"9:00am", "ended_time": "5:00pm"}'
    fi  

    CURRENT=$(date -d "$TMP_DATE + 1 day" "+%s")
done

